// ═══════════════════════════════════════
// DATA.JS — 인물·섹터·패턴·초기로그 데이터
// 수정은 이 파일만 건드릴 것
// ═══════════════════════════════════════

const FIGS = [
  {id:1,name:"Donald Trump",avatar:"DT",country:"🇺🇸",title:"미국 대통령",color:"#ff4444",
   twitter:"realDonaldTrump", googleAlert:"Donald Trump",
   inf:100,base:100,susp:95,chType:"소셜직접형",
   ch:["Truth Social @realDonaldTrump","백악관 기자회견","행정명령"],
   sec:["TRADE","ENERGY","CRYPTO","DEFENSE","FINANCE","RETAIL","HEALTHCARE"],
   rel:[{to:2,type:"동맹",str:85},{to:4,type:"갈등",str:90}]},
  {id:2,name:"Elon Musk",avatar:"EM",country:"🇺🇸",title:"Tesla·xAI CEO",color:"#ff8c00",
   twitter:"elonmusk", googleAlert:"Elon Musk",
   inf:97,base:97,susp:88,chType:"소셜직접형",
   ch:["X @elonmusk","Tesla 실적발표","제품 키노트"],
   sec:["AI","EV","CRYPTO","SPACE","ROBOT"],
   rel:[{to:1,type:"동맹",str:85},{to:5,type:"협력",str:72}]},
  {id:3,name:"Jerome Powell",avatar:"JP",country:"🇺🇸",title:"연준 의장",color:"#4a9eff",
   twitter:null, googleAlert:"Jerome Powell Federal Reserve",
   inf:91,base:91,susp:28,chType:"기관성명형",
   ch:["FOMC 성명 (일정고정)","의회 증언","잭슨홀 연설"],
   sec:["FINANCE","BOND","GOLD","REALESTATE"],rel:[]},
  {id:4,name:"Xi Jinping",avatar:"XJ",country:"🇨🇳",title:"중국 국가주석",color:"#ef4444",
   twitter:null, googleAlert:"Xi Jinping",
   inf:89,base:89,susp:67,chType:"정책발표형",
   ch:["신화사 영문판","당 대회 발표","인민일보"],
   sec:["SEMICON","CHINA_TECH","RARE_EARTH"],
   rel:[{to:1,type:"갈등",str:90}]},
  {id:5,name:"Jensen Huang",avatar:"JH",country:"🇺🇸",title:"NVIDIA CEO",color:"#76b900",
   twitter:"jensenhuang", googleAlert:"Jensen Huang NVIDIA",
   inf:84,base:84,susp:18,chType:"이벤트발표형",
   ch:["GTC 컨퍼런스 (연1회)","분기 실적발표","X @jensenhuang"],
   sec:["AI","SEMICON","CLOUD","ROBOT"],
   rel:[{to:2,type:"협력",str:72}]},
  {id:6,name:"Warren Buffett",avatar:"WB",country:"🇺🇸",title:"Berkshire 회장",color:"#c084fc",
   twitter:null, googleAlert:"Warren Buffett",
   inf:82,base:82,susp:22,chType:"인터뷰형",
   ch:["연간 주주서한 (2월)","13F 공시","CNBC 인터뷰"],
   sec:["FINANCE","RETAIL","ENERGY","HEALTHCARE"],rel:[]},
  {id:7,name:"Jamie Dimon",avatar:"JD",country:"🇺🇸",title:"JPMorgan CEO",color:"#06b6d4",
   twitter:null, googleAlert:"Jamie Dimon JPMorgan",
   inf:78,base:78,susp:31,chType:"인터뷰형",
   ch:["연간 주주서한","다보스 발언","Bloomberg 인터뷰"],
   sec:["FINANCE","BOND","CRYPTO","REALESTATE"],rel:[]},
  {id:8,name:"Sam Altman",avatar:"SA",country:"🇺🇸",title:"OpenAI CEO",color:"#10b981",
   twitter:"sama", googleAlert:"Sam Altman OpenAI",
   inf:74,base:74,susp:29,chType:"소셜직접형",
   ch:["X @sama","제품발표","의회 증언"],
   sec:["AI","CLOUD","SEMICON"],rel:[]},
  {id:9,name:"MBS",avatar:"MB",country:"🇸🇦",title:"사우디 왕세자",color:"#f97316",
   twitter:null, googleAlert:"MBS Saudi Arabia",
   inf:72,base:72,susp:55,chType:"정책발표형",
   ch:["OPEC+ 발표","사우디 국영미디어 SPA"],
   sec:["ENERGY","DEFENSE"],rel:[]},
];

const SM = {
  AI:{label:"AI·딥러닝",color:"#76b900",temp:88,
    d:[{t:"NVDA",n:"NVIDIA",f:92,mc:"3.1T",note:"AI칩 독점"},{t:"MSFT",n:"Microsoft",f:88,mc:"3.0T",note:"OpenAI+Azure"},{t:"GOOGL",n:"Alphabet",f:85,mc:"2.0T",note:"Gemini·TPU"}],
    i:[{t:"SMCI",n:"Super Micro",f:72,mc:"30B",note:"AI서버"},{t:"ANET",n:"Arista",f:80,mc:"120B",note:"DC네트워크"},{t:"ARM",n:"ARM Holdings",f:76,mc:"140B",note:"칩설계"}]},
  SEMICON:{label:"반도체",color:"#a78bfa",temp:72,
    d:[{t:"NVDA",n:"NVIDIA",f:92,mc:"3.1T",note:"GPU 독점"},{t:"AMD",n:"AMD",f:78,mc:"220B",note:"NVDA대안"},{t:"INTC",n:"Intel",f:52,mc:"90B",note:"구조조정中"}],
    i:[{t:"ASML",n:"ASML",f:90,mc:"280B",note:"EUV독점"},{t:"AMAT",n:"Applied Materials",f:82,mc:"140B",note:"반도체장비"},{t:"TSM",n:"TSMC ADR",f:91,mc:"900B",note:"파운드리1위"}]},
  EV:{label:"전기차·로봇",color:"#ff8c00",temp:45,
    d:[{t:"TSLA",n:"Tesla",f:61,mc:"800B",note:"브랜드리스크"},{t:"RIVN",n:"Rivian",f:44,mc:"15B",note:"적자지속"},{t:"LI",n:"Li Auto",f:71,mc:"25B",note:"중국내수"}],
    i:[{t:"ALB",n:"Albemarle",f:65,mc:"10B",note:"리튬원자재"},{t:"ON",n:"ON Semi",f:74,mc:"30B",note:"EV전력반도체"},{t:"APTV",n:"Aptiv",f:68,mc:"12B",note:"자율주행부품"}]},
  CRYPTO:{label:"크립토",color:"#f59e0b",temp:61,
    d:[{t:"COIN",n:"Coinbase",f:65,mc:"55B",note:"미국최대거래소"},{t:"MSTR",n:"MicroStrategy",f:58,mc:"80B",note:"BTC레버리지"},{t:"IBIT",n:"iShares BTC ETF",f:70,mc:"—",note:"BTC직접노출"}],
    i:[{t:"RIOT",n:"Riot Platforms",f:51,mc:"4B",note:"BTC채굴"},{t:"SQ",n:"Block",f:67,mc:"40B",note:"크립토결제"},{t:"CLSK",n:"CleanSpark",f:53,mc:"3B",note:"BTC채굴"}]},
  ENERGY:{label:"에너지",color:"#ef4444",temp:79,
    d:[{t:"XOM",n:"ExxonMobil",f:74,mc:"490B",note:"원유메이저"},{t:"CVX",n:"Chevron",f:72,mc:"270B",note:"원유메이저"},{t:"OXY",n:"Occidental",f:68,mc:"48B",note:"Buffett보유"}],
    i:[{t:"HAL",n:"Halliburton",f:66,mc:"28B",note:"유전서비스"},{t:"SLB",n:"SLB",f:70,mc:"60B",note:"오일필드1위"},{t:"FSLR",n:"First Solar",f:72,mc:"20B",note:"태양광"}]},
  FINANCE:{label:"금융·은행",color:"#06b6d4",temp:55,
    d:[{t:"JPM",n:"JPMorgan",f:85,mc:"700B",note:"미국최대은행"},{t:"BAC",n:"BofA",f:78,mc:"340B",note:"금리민감"},{t:"GS",n:"Goldman Sachs",f:82,mc:"180B",note:"M&A·트레이딩"}],
    i:[{t:"V",n:"Visa",f:88,mc:"600B",note:"결제인프라"},{t:"BRK.B",n:"Berkshire",f:86,mc:"1.0T",note:"Buffett펀드"},{t:"SCHW",n:"Schwab",f:74,mc:"130B",note:"리테일브로커"}]},
  CHINA_TECH:{label:"중국 테크",color:"#fbbf24",temp:38,
    d:[{t:"BABA",n:"Alibaba",f:67,mc:"250B",note:"이커머스·클라우드"},{t:"BIDU",n:"Baidu",f:59,mc:"30B",note:"검색·AI"},{t:"PDD",n:"PDD Holdings",f:71,mc:"130B",note:"테무모회사"}],
    i:[{t:"FXI",n:"China ETF",f:58,mc:"—",note:"중국대형주"},{t:"KWEB",n:"China Internet ETF",f:60,mc:"—",note:"인터넷ETF"},{t:"JD",n:"JD.com",f:62,mc:"45B",note:"이커머스"}]},
  ROBOT:{label:"로봇·자동화",color:"#10b981",temp:66,
    d:[{t:"TSLA",n:"Tesla(Optimus)",f:61,mc:"800B",note:"Optimus2027"},{t:"ISRG",n:"Intuitive Surgical",f:85,mc:"180B",note:"수술로봇"},{t:"ABB",n:"ABB Ltd",f:79,mc:"80B",note:"산업로봇"}],
    i:[{t:"NVDA",n:"NVIDIA",f:92,mc:"3.1T",note:"로봇AI두뇌"},{t:"TER",n:"Teradyne",f:74,mc:"15B",note:"로봇테스팅"},{t:"RKLB",n:"Rocket Lab",f:63,mc:"10B",note:"소형발사체"}]},
  DEFENSE:{label:"방위·우주",color:"#8b5cf6",temp:82,
    d:[{t:"LMT",n:"Lockheed Martin",f:80,mc:"130B",note:"F-35·미사일"},{t:"RTX",n:"RTX",f:77,mc:"150B",note:"레이더·미사일"},{t:"NOC",n:"Northrop",f:76,mc:"70B",note:"스텔스·우주"}],
    i:[{t:"PLTR",n:"Palantir",f:72,mc:"200B",note:"군사AI"},{t:"RKLB",n:"Rocket Lab",f:63,mc:"10B",note:"발사체"},{t:"HII",n:"Huntington Ingalls",f:70,mc:"10B",note:"해군함정"}]},
  HEALTHCARE:{label:"의료·바이오",color:"#ec4899",temp:60,
    d:[{t:"LLY",n:"Eli Lilly",f:88,mc:"750B",note:"비만약 독주"},{t:"UNH",n:"UnitedHealth",f:82,mc:"450B",note:"최대보험사"},{t:"JNJ",n:"J&J",f:79,mc:"390B",note:"의료복합기업"}],
    i:[{t:"MRNA",n:"Moderna",f:58,mc:"15B",note:"mRNA플랫폼"},{t:"PFE",n:"Pfizer",f:60,mc:"160B",note:"대형제약"},{t:"ISRG",n:"Intuitive Surgical",f:85,mc:"180B",note:"수술로봇"}]},
  RETAIL:{label:"소비·유통",color:"#f97316",temp:52,
    d:[{t:"AMZN",n:"Amazon",f:90,mc:"2.1T",note:"이커머스1위"},{t:"WMT",n:"Walmart",f:85,mc:"700B",note:"오프라인1위"},{t:"COST",n:"Costco",f:88,mc:"400B",note:"멤버십유통"}],
    i:[{t:"TGT",n:"Target",f:72,mc:"55B",note:"중가유통"},{t:"HD",n:"Home Depot",f:80,mc:"370B",note:"홈인테리어"},{t:"MCD",n:"McDonald's",f:83,mc:"210B",note:"패스트푸드"}]},
  REALESTATE:{label:"부동산·리츠",color:"#14b8a6",temp:44,
    d:[{t:"PLD",n:"Prologis",f:82,mc:"100B",note:"물류창고REIT"},{t:"AMT",n:"American Tower",f:78,mc:"90B",note:"통신타워REIT"},{t:"EQIX",n:"Equinix",f:84,mc:"80B",note:"데이터센터REIT"}],
    i:[{t:"SPG",n:"Simon Property",f:70,mc:"55B",note:"쇼핑몰REIT"},{t:"O",n:"Realty Income",f:74,mc:"50B",note:"월배당REIT"},{t:"WELL",n:"Welltower",f:75,mc:"70B",note:"헬스케어REIT"}]},
};

// ── 인물별 과거 패턴 데이터베이스
const PATTERNS = {
  1: { // Trump
    name: "Donald Trump",
    color: "#ff4444",
    patternScore: 94,
    signaturePatterns: [
      {
        id:"T1",
        name:"관세 쇼크 → 유예 사이클",
        type:"연출의심",
        frequency:"반복확인 3회",
        description:"강경 관세 발표로 시장 급락 유발 → 수일 내 유예·완화 발표 → 시장 급반등",
        avgDropPct: 8,
        avgRecoveryDays: 7,
        avgPureEffect: 6.5,
        suspicion: 92,
        examples:[
          {date:"2025-04-02", event:"상호관세 전면시행", drop:8, recovery:14},
          {date:"2025-04-09", event:"90일 유예 발표 전 'BUY' 트윗", drop:-9, recovery:0},
          {date:"2025-06-01", event:"EU 관세 50% → 유예", drop:5, recovery:5},
        ],
        signal:"관세 발표 → 급락 → 3~10일 내 완화 발표 패턴. 급락 시 매수 기회",
        actionOnDetect:"발표 당일 분할매수 시작 · 유예 발표 시 청산",
      },
      {
        id:"T2",
        name:"소셜 선행 매수 암시",
        type:"내부자거래의심",
        frequency:"2회 확인",
        description:"Truth Social에 매수 암시 포스팅 직후 정책 완화 발표. 내부 서클 사전 정보 의혹",
        avgDropPct: 0,
        avgRecoveryDays: 1,
        avgPureEffect: 9,
        suspicion: 95,
        examples:[
          {date:"2025-04-09", event:"'THIS IS A GREAT TIME TO BUY!!!' 트윗", drop:-9, recovery:0},
        ],
        signal:"Truth Social에 매수 암시 문구 등장 시 즉시 주목",
        actionOnDetect:"즉시 포지션 진입 검토 · 당일 내 정책 발표 가능성 높음",
      },
      {
        id:"T3",
        name:"크립토 Pump & Dump",
        type:"연출의심",
        frequency:"반복확인",
        description:"$TRUMP 밈코인 발행·홍보 후 내부 보유 물량 매도. 소매 투자자 피해",
        avgDropPct: 25,
        avgRecoveryDays: 0,
        avgPureEffect: 24,
        suspicion: 97,
        examples:[
          {date:"2025-01-17", event:"$TRUMP 밈코인 론칭", drop:0, recovery:0},
          {date:"2025-03-01", event:"$TRUMP 고점 후 80% 폭락", drop:80, recovery:0},
        ],
        signal:"Trump 관련 새 토큰·코인 발행 시 진입 금지 — Pump&Dump 구조",
        actionOnDetect:"절대 진입 금지 · 오히려 관련 거래소 주식 주의",
      },
    ],
    overallPattern:"발언→급락→유예 사이클 반복. SEC 무력화로 조사 불가. 발언 후 2~10일 내 원복 패턴 강함",
    patternBonus: +8,
  },
  2: { // Musk
    name: "Elon Musk",
    color: "#ff8c00",
    patternScore: 89,
    signaturePatterns: [
      {
        id:"M1",
        name:"SNS 급등락 트리거",
        type:"의도적조작의심",
        frequency:"반복확인 5회+",
        description:"X 트윗 한 줄로 크립토·주식 급등락 유발. DOGE 반복 언급으로 수혜",
        avgDropPct: 12,
        avgRecoveryDays: 14,
        avgPureEffect: 11,
        suspicion: 88,
        examples:[
          {date:"2021-05-13", event:"Tesla BTC결제 중단 선언", drop:15, recovery:28},
          {date:"2021-02-01", event:"DOGE 반복 트윗 → +800%", drop:-50, recovery:0},
          {date:"2025-06-05", event:"Trump 갈등 폭발 → DOGE -10%", drop:10, recovery:9},
        ],
        signal:"새벽 트윗 특히 주의 — 한국시간 오전 4~8시 집중",
        actionOnDetect:"트윗 확인 즉시 15분 내 종목 반응 체크",
      },
      {
        id:"M2",
        name:"Trump 갈등→화해 사이클",
        type:"연출의심",
        frequency:"2회 확인",
        description:"Trump와 공개 충돌 → 관련 종목 급락 → 3주 내 화해 → 완전 회복. 연출 가능성 높음",
        avgDropPct: 10,
        avgRecoveryDays: 21,
        avgPureEffect: 8,
        suspicion: 82,
        examples:[
          {date:"2025-06-05", event:"Big Beautiful Bill 갈등 폭발", drop:10, recovery:21},
          {date:"2022-07-01", event:"Twitter 갈등 → 화해", drop:8, recovery:18},
        ],
        signal:"갈등 폭발 시 TSLA·DOGE 분할매수 시작 · 화해 시그널 시 청산",
        actionOnDetect:"갈등 첫날 1/3 진입 · +1주 1/3 · 화해 시 전량 청산",
      },
      {
        id:"M3",
        name:"제품 발표 전후 급등",
        type:"정상패턴",
        frequency:"반복확인",
        description:"Tesla 신제품·FSD·Optimus 발표 전후 TSLA 급등. AI 키노트 전 NVDA 동반 상승",
        avgDropPct: -15,
        avgRecoveryDays: 0,
        avgPureEffect: -12,
        suspicion: 15,
        examples:[
          {date:"2025-11-19", event:"Nvidia 지지 트윗 → NVDA +3%", drop:-3, recovery:0},
        ],
        signal:"GTC·Tesla AI Day 1주 전부터 관련주 모니터링",
        actionOnDetect:"이벤트 5일 전 진입 검토 · 이벤트 당일 청산",
      },
    ],
    overallPattern:"SNS 발언 충격파 강하나 회복도 빠름. Trump 관계 상태(동맹/갈등) 파악이 핵심",
    patternBonus: +5,
  },
  3: { // Powell
    name: "Jerome Powell",
    color: "#4a9eff",
    patternScore: 76,
    signaturePatterns: [
      {
        id:"P1",
        name:"FOMC 충격 → 2주 회복",
        type:"정상패턴",
        frequency:"반복확인",
        description:"금리 동결·인상 발표 시 당일 급락 후 1~2주 내 회복. 예측 가능한 패턴",
        avgDropPct: 3,
        avgRecoveryDays: 10,
        avgPureEffect: 2,
        suspicion: 20,
        examples:[
          {date:"2025-09-01", event:"밸류에이션 고평가 경고", drop:2, recovery:7},
          {date:"2025-11-01", event:"금리 동결 + 인플레 우려", drop:1, recovery:5},
        ],
        signal:"FOMC 발표 당일 급락 시 단기 매수 기회. 2주 회복 패턴",
        actionOnDetect:"FOMC 당일 종가 매수 · 2주 후 청산",
      },
    ],
    overallPattern:"일정이 고정돼 있어 예측 가능. 발언 자체보다 시장 예상 대비 서프라이즈 여부가 관건",
    patternBonus: 0,
  },
  4: { // Xi
    name: "Xi Jinping",
    color: "#ef4444",
    patternScore: 71,
    signaturePatterns: [
      {
        id:"X1",
        name:"반도체 규제 카드",
        type:"지정학패턴",
        frequency:"반복확인",
        description:"미중 갈등 고조 시 반도체 수출제한 경고 → NVDA·TSM 급락. 그러나 실제 완전 차단은 미실행",
        avgDropPct: 6,
        avgRecoveryDays: 12,
        avgPureEffect: 5,
        suspicion: 65,
        examples:[
          {date:"2026-02-10", event:"반도체 수출제한 확대 경고", drop:5, recovery:12},
          {date:"2024-10-01", event:"갈륨·게르마늄 수출제한", drop:4, recovery:10},
        ],
        signal:"경고 발언 직후 NVDA·TSM·ASML 급락. 실제 입법까지 시간차 있음",
        actionOnDetect:"경고 발언 시 반도체 ETF SOXX 분할매수 검토",
      },
      {
        id:"X2",
        name:"대만 긴장 고조",
        type:"지정학패턴",
        frequency:"계절성",
        description:"연 1~2회 대만 관련 강경 발언 → 방위주 급등 / 테크주 급락",
        avgDropPct: 4,
        avgRecoveryDays: 20,
        avgPureEffect: 3.5,
        suspicion: 55,
        examples:[
          {date:"2024-05-01", event:"대만 훈련 발표", drop:3, recovery:15},
        ],
        signal:"방위주(LMT·RTX·NOC) 급등 · 테크주 급락 동시 발생",
        actionOnDetect:"방위주 롱 / 중국 테크주 관망",
      },
    ],
    overallPattern:"불규칙하나 반도체·대만 관련 발언 패턴 명확. 사전 감지 어려움 — 신화사 실시간 모니터 필수",
    patternBonus: +2,
  },
  5: { // Jensen Huang
    name: "Jensen Huang",
    color: "#76b900",
    patternScore: 82,
    signaturePatterns: [
      {
        id:"J1",
        name:"실적 발표 서프라이즈",
        type:"정상패턴",
        frequency:"분기마다",
        description:"분기 실적 발표 시 가이던스 상향 반복 → 시간외 +5~10%. 다음날 갭업",
        avgDropPct: -7,
        avgRecoveryDays: 0,
        avgPureEffect: -6,
        suspicion: 10,
        examples:[
          {date:"2025-11-19", event:"Q3 실적 + 가이던스 상향", drop:-6, recovery:0},
          {date:"2025-08-01", event:"Q2 실적 서프라이즈", drop:-8, recovery:0},
        ],
        signal:"실적 발표 전날 진입 · 당일 갭업 시 청산",
        actionOnDetect:"실적일 2일 전 진입 · 발표 후 갭업 시 일부 청산",
      },
      {
        id:"J2",
        name:"GTC 키노트 랠리",
        type:"정상패턴",
        frequency:"연1회 (3월)",
        description:"GTC 컨퍼런스 키노트 발표 전후 NVDA 10~20% 랠리. AI 관련주 동반 상승",
        avgDropPct: -12,
        avgRecoveryDays: 0,
        avgPureEffect: -10,
        suspicion: 8,
        examples:[
          {date:"2025-03-01", event:"GTC 2025 키노트 — 블랙웰 발표", drop:-15, recovery:0},
        ],
        signal:"GTC 1주 전부터 NVDA·SMCI·ANET 동반 상승 패턴",
        actionOnDetect:"GTC 2주 전 진입 · 키노트 당일 일부 청산",
      },
    ],
    overallPattern:"조작 의심 없음. 실적·이벤트 기반 예측 가능한 상승 패턴. 캘린더 등록만으로 선제 대응 가능",
    patternBonus: +3,
  },
};

const INIT_LOGS = [
  {id:1,figId:1,date:"2025-04-02",type:"부정",stmt:"상호관세 전면 시행 발표",
   tickers:"SPY,XOM",drop:8,spDrop:7,sectorDrop:6,recovery:14,verified:true,
   note:"관세 전면시행 — 시장 전반 하락"},
  {id:2,figId:1,date:"2025-04-09",type:"긍정",stmt:"THIS IS A GREAT TIME TO BUY! → 90일 유예",
   tickers:"SPY,NVDA",drop:-9,spDrop:-8,sectorDrop:-7,recovery:0,verified:true,
   note:"유예발표 당일 역대급 급등"},
  {id:3,figId:2,date:"2021-05-13",type:"부정",stmt:"Tesla BTC결제 중단 발표",
   tickers:"TSLA,COIN",drop:15,spDrop:1,sectorDrop:2,recovery:28,verified:true,
   note:"발언 순수효과 높음 — 시장무관 개별 급락"},
  {id:4,figId:2,date:"2025-06-05",type:"부정",stmt:"Trump-Musk 갈등 폭발 (연출 의심)",
   tickers:"DOGE,TSLA",drop:10,spDrop:1,sectorDrop:3,recovery:9,verified:false,
   note:"갈등 연출 가능성 — 빠른 화해로 회복"},
  {id:5,figId:5,date:"2025-11-19",type:"긍정",stmt:"Q3 실적+가이던스 상향 발표",
   tickers:"NVDA,AMD",drop:-6,spDrop:-1,sectorDrop:-2,recovery:0,verified:true,
   note:"실적 서프라이즈 — 시간외 +5.7%"},
  {id:6,figId:4,date:"2026-02-10",type:"부정",stmt:"반도체 수출제한 확대 경고",
   tickers:"NVDA,TSM",drop:5,spDrop:1,sectorDrop:4,recovery:12,verified:true,
   note:"중국발 규제 — 반도체 섹터 집중 타격"},
];
